version: 2
updates:
  - package-ecosystem: gradle
    directory: "/"
    schedule:
      interval: daily
    allow:
    - dependency-name: "alpha"
      update-types: ["version-update:semver-major"]
    open-pull-requests-limit: 10